stages:
  - update-dependencies
  - test-and-qa
  - build
  - sentry
  - release

variables:
  PROJECT_VERSION: '1.0'

cache:
  paths:
    - node_modules

default:
  image: node:latest

test-and-qa:
  image: cypress/base:12.13.0
  stage: test-and-qa
  except:
    - schedules
    - tags
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    name: $CI_COMMIT_REF_NAME
    expire_in: 1h
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run lint
    - npm run test:ci
    - npm run e2e:ci:concurrent

build:
  stage: build
  except:
    - schedules
  cache:
    policy: pull
  artifacts:
    paths:
      - dist/*
  only:
    refs:
      - master
  script:
    - npm run build

sentry:
  image: getsentry/sentry-cli
  stage: sentry
  except:
    - schedules
  only:
    refs:
      - master
  script:
    - sentry-cli releases new $CI_COMMIT_SHA
    - sentry-cli releases set-commits --auto $CI_COMMIT_SHA
    - sentry-cli releases files $CI_COMMIT_SHA upload-sourcemaps $CI_PROJECT_DIR/dist -x .js -x .map --validate --verbose --rewrite --strip-common-prefix
    - sentry-cli releases finalize $CI_COMMIT_SHA

release:
  stage: release
  except:
    - schedules
  only:
    refs:
      - master
  script:
    - npm run semantic-release

update-dependencies:
  only:
    - schedules
  stage: update-dependencies
  before_script:
    - npm ci
  script:
    - npm run update-dependencies
