stages:
  - update-dependencies
  - test-and-qa
  - build
  - release
  - deploy

variables:
  PROJECT_VERSION: '1.0'

cache:
  paths:
    - node_modules

default:
  image: node:latest

test-and-qa:
  image: cypress/base:12.13.0
  stage: test-and-qa
  except:
    - schedules
    - tags
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    name: $CI_COMMIT_REF_NAME
    expire_in: 1 days
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run lint
    - npm run test:ci
    - npm run e2e:ci:concurrent

build:
  stage: build
  except:
    - schedules
  cache:
    policy: pull
  artifacts:
    expire_in: 1 days
    paths:
      - dist/*
  only:
    refs:
      - master
  script:
    - npm run build

release:
  stage: release
  except:
    - schedules
  only:
    refs:
      - master
  script:
    - npm run release

update-dependencies:
  only:
    - schedules
  stage: update-dependencies
  before_script:
    - npm ci
  script:
    - npm run update-dependencies

pages:
  stage: deploy
  only:
    - master
  cache:
    policy: pull
  script:
    - mkdir public/$CI_COMMIT_REF_NAME
    - mv dist/* public/$CI_COMMIT_REF_NAME
    - echo "Frontend deployed on URL $CI_PAGES_URL/$CI_COMMIT_REF_NAME"
  artifacts:
    expire_in: 1 days
    paths:
      - public
