stages:
  - test
  - e2e
  - build
  - release
  - deploy

variables:
  PROJECT_VERSION: '1.0'

default:
  image: node:latest
  tags:
    - aws

test-and-qa:
  image: timbru31/java-node:11
  stage: test
  except:
    - schedules
    - tags
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules
      - .jest-cache
      - src/app/api
  script:
    - npm ci
    - npm run lint
    - npm run test:ci

test-e2e:
  image: cypress/base:14.16.0
  stage: e2e
  only:
    changes:
      - "src/**/*.ts"
      - "src/**/*.html"
      - "src/**/*.scss"
      - "src/**/*.js"
      - "package.json"
      - "package-lock.json"
      - "*.yml"
  except:
    - schedules
    - tags
    - src/app/api
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules
    policy: pull
  script:
    - npm ci
    - npm run e2e:ci:concurrent

build:
  image: timbru31/java-node:11
  stage: build
  except:
    - schedules
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules
    policy: pull
  artifacts:
    expire_in: 1 days
    paths:
      - dist/*
  only:
    refs:
      - master
  script:
    - npm run build

release:
  stage: release
  except:
    - schedules
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules
    policy: pull
  only:
    refs:
      - master
  script:
    - npm run release

cloudfront:
  stage: deploy
  except:
    - schedules
  only:
    - master
  environment:
    name: dev
    url: https://angular.redfroggy.io
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules
    policy: pull
  script:
    - npm run aws-deploy -- -c domain=$DOMAIN -c subdomain=$SUBDOMAIN -c certificateArn=$CERTIFICATE_ARN
