version: 2 # use CircleCI 2.0

job_defaults: &job_defaults
  docker:
    - image: circleci/openjdk

cache_key: &cache_key angular-starter-kit-v1-deps-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
dist_key: &dist_key angular-starter-kit-v1-dist-{{ .Revision }}

jobs:
  install:
    <<: *job_defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: *cache_key
      - run: apt-get update && apt-get -y install curl
      - run: curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get -y install nodejs
      - run: npm ci
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: apt-get update && apt-get -y install curl
      - run: curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get -y install nodejs
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run build
      - save_cache:
          key: *dist_key
          paths:
            - dist

  release:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_key
      - run: apt-get update && apt-get -y install curl
      - run: curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get -y install nodejs
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run: cp package.json dist/main
      - run: npm run semantic-release

workflows:
  version: 2
  build-test-release:
    jobs:
      - install
      - build:
          requires:
            - install
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
